### PR TITLE
Revert "feat: allow custom GET parameters in connection.server (fixes #27)"

### LINKED ISSUE #27: GET parameters in server URL are not carried through as such for upload url
Given that I pass in a custom `GET` parameter as the `server` config option,
`https://example.org/?spnego=disabled`,
the `GET` parameter is treated as part of the host url, not as url parameter:
`https://example.org/?spnego=disabled/sap/bc/adt/cts/transports`

Valid (upload) scenarios for this are to bypass SAML2 and SPNEGO authentication (`?saml2=disabled ?spnego=disabled`)

I will provide a fix for this as a PR - just keeping track of the issue here 😄

### PR DESCRIPTION
**Pull request by pfefferf**
Reverts pfefferf/ui5-nwabap-deployer#28

All standard cases failing because of wrong URL building.

### CODE REVIEW

**Comment by vobu** [comment]
any chance you can share the way you test so i can follow-up?

**Comment by pfefferf** [comment]
Regarding testing: [Here](https://github.com/pfefferf/ui5-nwabap-deployer/tree/master/packages/ui5-app) are some ui5 yaml files for different scenario. Just a .env file needs to be provided which sets the connection information (like server, user, pwd). 

In the meantime I provided a configuration option `customQueryParams` which allows you to set the additional parameters in a - from my point of view - more convenient way (instead of splitting of the server url + internal re-construction).

**Comment by vobu** [comment]
excellent, thanks for following up with the custom query params config option!
initially i thought about this as well but didn't want to disrupt too much of the existing configuration. 
anyway, do you need me to do anything else?

**Comment by pfefferf** [comment]
Just some small test if your requirement is fulfilled :)

**Comment by vobu** [comment]
Test w/ custom query params unfortunately didn't work, see #30 :(

**Pull request merged**
